/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981__factory } from "./IERC2981__factory";
export { LibPart__factory } from "./LibPart__factory";
export { LibRoyalties2981__factory } from "./LibRoyalties2981__factory";
export { RoyaltiesV2__factory } from "./RoyaltiesV2__factory";
