/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LibRoyalties2981,
  LibRoyalties2981Interface,
} from "../../../royalties/RoyaltiesUtils.sol/LibRoyalties2981";

const _abi = [
  {
    inputs: [],
    name: "RoyaltyOverflow",
    type: "error",
  },
];

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000804000a";

type LibRoyalties2981ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibRoyalties2981ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibRoyalties2981__factory extends ContractFactory {
  constructor(...args: LibRoyalties2981ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibRoyalties2981> {
    return super.deploy(overrides || {}) as Promise<LibRoyalties2981>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibRoyalties2981 {
    return super.attach(address) as LibRoyalties2981;
  }
  override connect(signer: Signer): LibRoyalties2981__factory {
    return super.connect(signer) as LibRoyalties2981__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibRoyalties2981Interface {
    return new utils.Interface(_abi) as LibRoyalties2981Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibRoyalties2981 {
    return new Contract(address, _abi, signerOrProvider) as LibRoyalties2981;
  }
}
