/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as royaltiesBaseSol from "./RoyaltiesBase.sol";
export * as royaltiesUtilsSol from "./RoyaltiesUtils.sol";
