/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AbstractRoyalties } from "./AbstractRoyalties";
export type { RoyaltiesV2Impl } from "./RoyaltiesV2Impl";
