/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AbstractRoyalties,
  AbstractRoyaltiesInterface,
} from "../../../royalties/RoyaltiesBase.sol/AbstractRoyalties";

const _abi = [
  {
    inputs: [],
    name: "MissingRecipient",
    type: "error",
  },
  {
    inputs: [],
    name: "RoyaltiesCantBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "RoyaltyOverflow",
    type: "error",
  },
];

export class AbstractRoyalties__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractRoyaltiesInterface {
    return new utils.Interface(_abi) as AbstractRoyaltiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractRoyalties {
    return new Contract(address, _abi, signerOrProvider) as AbstractRoyalties;
  }
}
