/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AbstractRoyalties__factory } from "./AbstractRoyalties__factory";
export { RoyaltiesV2Impl__factory } from "./RoyaltiesV2Impl__factory";
