/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Delegate__factory } from "./Delegate__factory";
export { ERC721MGasReporter__factory } from "./ERC721MGasReporter__factory";
