/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC2981 } from "./IERC2981";
export type { LibPart } from "./LibPart";
export type { LibRoyalties2981 } from "./LibRoyalties2981";
export type { RoyaltiesV2 } from "./RoyaltiesV2";
