/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as royaltiesBaseSol from "./RoyaltiesBase.sol";
export type { royaltiesBaseSol };
import type * as royaltiesUtilsSol from "./RoyaltiesUtils.sol";
export type { royaltiesUtilsSol };
